import bcrypt from "bcryptjs";
import "dotenv/config";
import { PrismaClient } from "../node_modules/.prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const hashPassword = (pw: string) => bcrypt.hash(pw, 10);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("🌱 开始造种子数据...");

  await prisma.message.deleteMany();
  await prisma.carSource.deleteMany();
  await prisma.article.deleteMany();
  await prisma.model.deleteMany();
  await prisma.brand.deleteMany();
  await prisma.session.deleteMany();
  await prisma.user.deleteMany();

  // === 品牌 ===
  const b: Record<string, { id: string }> = {};
  b["比亚迪"] = await prisma.brand.create({ data: { name: "比亚迪", country: "中国", logoUrl: "/brands/比亚迪.svg" } });
  b["特斯拉"] = await prisma.brand.create({ data: { name: "特斯拉", country: "美国", logoUrl: "/brands/特斯拉.svg" } });
  b["蔚来"] = await prisma.brand.create({ data: { name: "蔚来", country: "中国", logoUrl: "/brands/蔚来.svg" } });
  b["小鹏"] = await prisma.brand.create({ data: { name: "小鹏", country: "中国", logoUrl: "/brands/小鹏.svg" } });
  b["理想"] = await prisma.brand.create({ data: { name: "理想", country: "中国", logoUrl: "/brands/理想.svg" } });
  b["极氪"] = await prisma.brand.create({ data: { name: "极氪", country: "中国", logoUrl: "/brands/极氪.svg" } });
  b["阿维塔"] = await prisma.brand.create({ data: { name: "阿维塔", country: "中国", logoUrl: "/brands/阿维塔.svg" } });
  b["大众"] = await prisma.brand.create({ data: { name: "大众", country: "德国", logoUrl: "/brands/大众.svg" } });
  b["丰田"] = await prisma.brand.create({ data: { name: "丰田", country: "日本", logoUrl: "/brands/丰田.svg" } });
  b["宝马"] = await prisma.brand.create({ data: { name: "宝马", country: "德国", logoUrl: "/brands/宝马.svg" } });
  b["吉利银河"] = await prisma.brand.create({ data: { name: "吉利银河", country: "中国", logoUrl: "/brands/吉利银河.svg" } });
  b["吉利"] = await prisma.brand.create({ data: { name: "吉利", country: "中国", logoUrl: "/brands/吉利.svg" } });
  b["小米"] = await prisma.brand.create({ data: { name: "小米", country: "中国", logoUrl: "/brands/小米.svg" } });
  b["零跑"] = await prisma.brand.create({ data: { name: "零跑", country: "中国", logoUrl: "/brands/零跑.svg" } });
  b["问界"] = await prisma.brand.create({ data: { name: "问界", country: "中国", logoUrl: "/brands/问界.svg" } });
  b["五菱"] = await prisma.brand.create({ data: { name: "五菱", country: "中国", logoUrl: "/brands/五菱.svg" } });
  b["奇瑞"] = await prisma.brand.create({ data: { name: "奇瑞", country: "中国", logoUrl: "/brands/奇瑞.svg" } });
  b["哈弗"] = await prisma.brand.create({ data: { name: "哈弗", country: "中国", logoUrl: "/brands/哈弗.svg" } });
  b["长安"] = await prisma.brand.create({ data: { name: "长安", country: "中国", logoUrl: "/brands/长安.svg" } });
  b["深蓝"] = await prisma.brand.create({ data: { name: "深蓝", country: "中国", logoUrl: "/brands/深蓝.svg" } });
  b["腾势"] = await prisma.brand.create({ data: { name: "腾势", country: "中国", logoUrl: "/brands/腾势.svg" } });
  b["方程豹"] = await prisma.brand.create({ data: { name: "方程豹", country: "中国", logoUrl: "/brands/方程豹.svg" } });
  b["日产"] = await prisma.brand.create({ data: { name: "日产", country: "日本", logoUrl: "/brands/日产.svg" } });
  b["本田"] = await prisma.brand.create({ data: { name: "本田", country: "中国", logoUrl: "/brands/本田.svg" } });
  b["别克"] = await prisma.brand.create({ data: { name: "别克", country: "美国", logoUrl: "/brands/别克.svg" } });
  b["奔驰"] = await prisma.brand.create({ data: { name: "奔驰", country: "德国", logoUrl: "/brands/奔驰.svg" } });
  b["奥迪"] = await prisma.brand.create({ data: { name: "奥迪", country: "德国", logoUrl: "/brands/奥迪.svg" } });
  b["领克"] = await prisma.brand.create({ data: { name: "领克", country: "中国", logoUrl: "/brands/领克.svg" } });
  b["红旗"] = await prisma.brand.create({ data: { name: "红旗", country: "中国", logoUrl: "/brands/红旗.svg" } });
  b["广汽埃安"] = await prisma.brand.create({ data: { name: "广汽埃安", country: "中国", logoUrl: "/brands/广汽埃安.svg" } });
  b["捷途"] = await prisma.brand.create({ data: { name: "捷途", country: "中国", logoUrl: "/brands/捷途.svg" } });
  b["岚图"] = await prisma.brand.create({ data: { name: "岚图", country: "中国", logoUrl: "/brands/岚图.svg" } });
  b["哪吒"] = await prisma.brand.create({ data: { name: "哪吒", country: "中国", logoUrl: "/brands/哪吒.svg" } });
  b["保时捷"] = await prisma.brand.create({ data: { name: "保时捷", country: "德国", logoUrl: "/brands/保时捷.svg" } });
  b["沃尔沃"] = await prisma.brand.create({ data: { name: "沃尔沃", country: "瑞典", logoUrl: "/brands/沃尔沃.svg" } });

  // === 车型 ===
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "海鸥", slug: "byd-seagull", level: "轿车", priceMin: 6.98, priceMax: 8.58, evType: "纯电", salesVolume2025: 529537, imageUrl: null, motorType: '永磁同步', motorPower: 55, motorTorque: 135, batteryCapacity: 30.08, batteryType: '磷酸铁锂', rangeCLTC: 305, topSpeed: 130, length: 3780, width: 1715, height: 1540, wheelbase: 2500, weight: 1200, seats: 4, trunkVolume: 930, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '扭力梁', adasLevel: 'L2', screen: '10.1英寸', ota: true, carPlay: true, chargeSlow: 4.5, voltage: '400V', sunroof: '无', wheels: '15英寸', headlights: 'LED', hiddenHandle: false, electricTail: false, seatMaterial: '织物', seatVentHeat: '无', steeringHeat: false, airbags: 4, tirePressure: '直接', autoBrake: true, blindSpot: false, acType: '手动', airPurifier: false, wirelessCharge: false, keyless: true, remoteControl: 'APP远程', lka: false, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["吉利银河"].id, name: "星愿", slug: "geely-xingyuan", level: "轿车", priceMin: 6.88, priceMax: 9.78, evType: "纯电", salesVolume2025: 478960, imageUrl: null, motorType: '永磁同步', motorPower: 85, motorTorque: 180, batteryCapacity: 31.97, batteryType: '磷酸铁锂', rangeCLTC: 310, topSpeed: 135, length: 4135, width: 1805, height: 1570, wheelbase: 2650, weight: 1330, seats: 5, trunkVolume: 540, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '扭力梁', chip: '吉利龙鹰', adasLevel: 'L2', screen: '14.6英寸', ota: true, carPlay: true, chargeSlow: 4.5, chargePower: 40, voltage: '400V', sunroof: '全景天窗', wheels: '16英寸', headlights: 'LED', hiddenHandle: true, electricTail: false, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["五菱"].id, name: "宏光MINIEV", slug: "wuling-hongguang-mini-ev", level: "轿车", priceMin: 3.58, priceMax: 5.58, evType: "纯电", salesVolume2025: 440687, imageUrl: null, motorType: '永磁同步', motorPower: 20, motorTorque: 85, batteryCapacity: 9.3, batteryType: '磷酸铁锂', rangeCLTC: 120, topSpeed: 100, length: 3043, width: 1520, height: 1590, wheelbase: 1965, weight: 660, seats: 4, trunkVolume: 180, driveMode: '后驱', suspensionF: '麦弗逊', suspensionR: '多连杆', screen: '7英寸', ota: false, carPlay: false, chargeSlow: 4.5, voltage: '400V', sunroof: '无', wheels: '12英寸', headlights: '卤素', hiddenHandle: false, electricTail: false, seatMaterial: '织物', seatVentHeat: '无', steeringHeat: false, airbags: 2, autoBrake: false, blindSpot: false, acType: '手动', airPurifier: false, wirelessCharge: false, keyless: false, lka: false, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "秦PLUS DM-i", slug: "byd-qin-plus-dmi", level: "轿车", priceMin: 9.98, priceMax: 17.58, evType: "插混", salesVolume2025: 366090, imageUrl: null, motorPower: 132, motorTorque: 316, batteryCapacity: 8.32, batteryType: '磷酸铁锂', rangeCLTC: 55, fuelConsumption: 3.8, enginePower: 74, engineTorque: 126, length: 4765, width: 1837, height: 1495, wheelbase: 2718, weight: 1530, seats: 5, trunkVolume: 500, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '扭力梁', adasLevel: 'L2', screen: '10.1英寸', ota: true, carPlay: true, voltage: '400V', sunroof: '单天窗', wheels: '16英寸', headlights: 'LED', hiddenHandle: false, electricTail: false, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, airbags: 4, tirePressure: '直接', autoBrake: true, blindSpot: false, acType: '自动', airPurifier: true, wirelessCharge: false, keyless: true, remoteControl: 'APP远程', acc: '定速', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["日产"].id, name: "轩逸", slug: "nissan-sylphy", level: "轿车", priceMin: 9.98, priceMax: 17.49, evType: "燃油", salesVolume2025: 315019, imageUrl: null, fuelType: '92#', fuelConsumption: 5.2, enginePower: 90, engineTorque: 155, length: 4652, width: 1815, height: 1450, wheelbase: 2712, weight: 1280, seats: 5, trunkVolume: 560, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '扭力梁', adasLevel: 'L2', screen: '8英寸', ota: false, carPlay: true, sunroof: '单天窗', wheels: '16英寸', headlights: 'LED', hiddenHandle: false, electricTail: false, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: false, acType: '自动', airPurifier: false, wirelessCharge: false, keyless: true, lka: false, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["特斯拉"].id, name: "Model 3", slug: "tesla-model-3", level: "轿车", priceMin: 24.59, priceMax: 33.99, evType: "纯电", salesVolume2025: 312738, imageUrl: null, motorType: '永磁同步', motorPower: 194, motorTorque: 340, batteryCapacity: 60, batteryType: '三元锂', rangeCLTC: 606, acceleration: 6.1, topSpeed: 200, length: 4720, width: 1848, height: 1442, wheelbase: 2875, weight: 1760, seats: 5, trunkVolume: 425, driveMode: '后驱', suspensionF: '双叉臂', suspensionR: '多连杆', chip: 'HW4.0(FSD)', adasLevel: 'L2+', screen: '15.4英寸', ota: true, carPlay: false, chargeFast: 25, chargeSlow: 10, chargePower: 170, voltage: '400V', sunroof: '全景天窗', wheels: '18英寸', headlights: 'LED', hiddenHandle: true, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: true, ambientLight: '多色', airbags: 8, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+手机钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: true, nop: '城市NOA' } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "秦L", slug: "byd-qin-l", level: "轿车", priceMin: 9.98, priceMax: 15.98, evType: "插混", salesVolume2025: 287489, imageUrl: null, motorPower: 120, motorTorque: 280, batteryCapacity: 10.08, batteryType: '磷酸铁锂', rangeCLTC: 80, fuelConsumption: 2.9, enginePower: 74, engineTorque: 126, length: 4830, width: 1900, height: 1495, wheelbase: 2790, weight: 1660, seats: 5, trunkVolume: 450, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', chip: '地平线征程3', adasLevel: 'L2', screen: '12.8英寸', ota: true, carPlay: true, voltage: '400V', sunroof: '全景天窗', wheels: '16英寸', headlights: 'LED', hiddenHandle: true, electricTail: false, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["小米"].id, name: "SU7", slug: "xiaomi-su7", level: "轿车", priceMin: 21.59, priceMax: 29.99, evType: "纯电", salesVolume2025: 258164, imageUrl: null, motorType: '永磁同步', motorPower: 220, motorTorque: 400, batteryCapacity: 73.6, batteryType: '磷酸铁锂', rangeCLTC: 668, acceleration: 5.7, topSpeed: 210, length: 4997, width: 1953, height: 1455, wheelbase: 3000, weight: 1980, seats: 5, trunkVolume: 517, driveMode: '后驱', suspensionF: '双叉臂', suspensionR: '多连杆', chip: '骁龙8295', adasLevel: 'L2+', screen: '16.1英寸', ota: true, carPlay: true, chargeFast: 15, chargeSlow: 8, chargePower: 220, voltage: '800V', sunroof: '全景天窗', wheels: '19英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 9, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: true, nop: '城市NOA' } });
  await prisma.model.create({ data: { brandId: b["大众"].id, name: "速腾", slug: "vw-sagitar", level: "轿车", priceMin: 12.79, priceMax: 17.29, evType: "燃油", salesVolume2025: 251918, imageUrl: null, fuelType: '95#', fuelConsumption: 5.7, enginePower: 110, engineTorque: 250, length: 4791, width: 1801, height: 1465, wheelbase: 2731, weight: 1410, seats: 5, trunkVolume: 553, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', adasLevel: 'L2', screen: '12英寸', ota: false, carPlay: true, sunroof: '全景天窗', wheels: '17英寸', headlights: 'LED', hiddenHandle: false, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: false, acType: '双区自动', airPurifier: false, wirelessCharge: true, keyless: true, acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["大众"].id, name: "朗逸", slug: "vw-lavida", level: "轿车", priceMin: 9.99, priceMax: 15.69, evType: "燃油", salesVolume2025: 270477, imageUrl: null, fuelType: '92#', fuelConsumption: 5.4, enginePower: 81, engineTorque: 141, length: 4670, width: 1806, height: 1474, wheelbase: 2688, weight: 1310, seats: 5, trunkVolume: 510, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '扭力梁', adasLevel: 'L2', screen: '8英寸', ota: false, carPlay: true, sunroof: '单天窗', wheels: '15英寸', headlights: 'LED', hiddenHandle: false, electricTail: false, seatMaterial: '织物', seatVentHeat: '无', steeringHeat: false, airbags: 4, tirePressure: '直接', autoBrake: true, blindSpot: false, acType: '手动', airPurifier: false, wirelessCharge: false, keyless: true, lka: false, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["特斯拉"].id, name: "Model Y", slug: "tesla-model-y", level: "SUV", priceMin: 26.39, priceMax: 36.39, evType: "纯电", salesVolume2025: 425337, imageUrl: null, motorType: '永磁同步', motorPower: 220, motorTorque: 440, batteryCapacity: 78.4, batteryType: '三元锂', rangeCLTC: 688, acceleration: 5.0, topSpeed: 217, length: 4750, width: 1921, height: 1624, wheelbase: 2890, weight: 1980, seats: 5, trunkVolume: 854, driveMode: '四驱', suspensionF: '双叉臂', suspensionR: '多连杆', chip: 'HW4.0(FSD)', adasLevel: 'L2+', screen: '15.4英寸', ota: true, carPlay: false, chargeFast: 25, chargeSlow: 10, chargePower: 170, voltage: '400V', sunroof: '全景天窗', wheels: '19英寸', headlights: 'LED', hiddenHandle: true, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: true, ambientLight: '多色', airbags: 8, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+手机钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: true, nop: '城市NOA' } });
  await prisma.model.create({ data: { brandId: b["吉利银河"].id, name: "星越L", slug: "geely-xingyue-l", level: "SUV", priceMin: 13.72, priceMax: 18.52, evType: "燃油", salesVolume2025: 244068, imageUrl: null, fuelType: '92#', fuelConsumption: 6.8, enginePower: 160, engineTorque: 325, length: 4770, width: 1895, height: 1689, wheelbase: 2845, weight: 1650, seats: 5, trunkVolume: 620, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', chip: '高通8155', adasLevel: 'L2', screen: '三联屏', ota: true, carPlay: true, sunroof: '全景天窗', wheels: '19英寸', headlights: '矩阵LED', hiddenHandle: false, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["丰田"].id, name: "RAV4荣放", slug: "toyota-rav4", level: "SUV", priceMin: 17.58, priceMax: 26.38, evType: "燃油", salesVolume2025: 204125, imageUrl: null, fuelType: '92#', fuelConsumption: 6.4, enginePower: 126, engineTorque: 209, length: 4600, width: 1855, height: 1680, wheelbase: 2690, weight: 1580, seats: 5, trunkVolume: 580, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '双叉臂', adasLevel: 'L2', screen: '10.25英寸', ota: false, carPlay: true, sunroof: '全景天窗', wheels: '18英寸', headlights: 'LED', hiddenHandle: false, electricTail: true, seatMaterial: '真皮', seatVentHeat: '仅加热', steeringHeat: false, airbags: 7, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: false, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["大众"].id, name: "途观L", slug: "vw-tiguan-l", level: "SUV", priceMin: 18.68, priceMax: 26.68, evType: "燃油", salesVolume2025: 202904, imageUrl: null, fuelType: '95#', fuelConsumption: 7.0, enginePower: 137, engineTorque: 320, length: 4733, width: 1839, height: 1673, wheelbase: 2791, weight: 1720, seats: 5, trunkVolume: 495, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', adasLevel: 'L2', screen: '12英寸', ota: false, carPlay: true, sunroof: '全景天窗', wheels: '19英寸', headlights: '矩阵LED', hiddenHandle: false, electricTail: true, seatMaterial: '真皮', seatVentHeat: '仅加热', steeringHeat: true, ambientLight: '多色', airbags: 7, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: false } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "宋Plus DM-i", slug: "byd-song-plus-dmi", level: "SUV", priceMin: 15.48, priceMax: 21.98, evType: "插混", salesVolume2025: 200276, imageUrl: null, motorPower: 145, motorTorque: 325, batteryCapacity: 18.3, batteryType: '磷酸铁锂', rangeCLTC: 110, fuelConsumption: 4.5, enginePower: 81, engineTorque: 135, length: 4775, width: 1890, height: 1670, wheelbase: 2765, weight: 1830, seats: 5, trunkVolume: 574, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', chip: '地平线征程3', adasLevel: 'L2', screen: '12.8英寸', ota: true, carPlay: true, chargeSlow: 3.5, voltage: '400V', sunroof: '全景天窗', wheels: '19英寸', headlights: 'LED', hiddenHandle: false, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "元UP", slug: "byd-yuan-up", level: "SUV", priceMin: 9.68, priceMax: 12.48, evType: "纯电", salesVolume2025: 189277, imageUrl: null, motorType: '永磁同步', motorPower: 130, motorTorque: 290, batteryCapacity: 45.12, batteryType: '磷酸铁锂', rangeCLTC: 401, topSpeed: 160, length: 4310, width: 1830, height: 1675, wheelbase: 2620, weight: 1580, seats: 5, trunkVolume: 450, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '扭力梁', adasLevel: 'L2', screen: '12.8英寸', ota: true, carPlay: true, chargeSlow: 7, voltage: '400V', sunroof: '全景天窗', wheels: '17英寸', headlights: 'LED', hiddenHandle: false, electricTail: false, seatMaterial: '仿皮', seatVentHeat: '无', steeringHeat: false, airbags: 4, tirePressure: '直接', autoBrake: true, blindSpot: false, acType: '自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "宋Pro DM-i", slug: "byd-song-pro-dmi", level: "SUV", priceMin: 10.98, priceMax: 15.98, evType: "插混", salesVolume2025: 180661, imageUrl: null, motorPower: 120, motorTorque: 280, batteryCapacity: 12.9, batteryType: '磷酸铁锂', rangeCLTC: 75, fuelConsumption: 4.4, enginePower: 74, engineTorque: 126, length: 4735, width: 1860, height: 1710, wheelbase: 2712, weight: 1730, seats: 5, trunkVolume: 520, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', adasLevel: 'L2', screen: '12.8英寸', ota: true, carPlay: true, voltage: '400V', sunroof: '全景天窗', wheels: '18英寸', headlights: 'LED', hiddenHandle: false, electricTail: false, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: false, acType: '自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["奇瑞"].id, name: "瑞虎8", slug: "chery-tiggo-8", level: "SUV", priceMin: 10.99, priceMax: 16.89, evType: "燃油", salesVolume2025: 179465, imageUrl: null, fuelType: '92#', fuelConsumption: 7.0, enginePower: 115, engineTorque: 230, length: 4722, width: 1860, height: 1745, wheelbase: 2710, weight: 1590, seats: 7, trunkVolume: 889, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', adasLevel: 'L2', screen: '12.3英寸', ota: true, carPlay: true, sunroof: '全景天窗', wheels: '18英寸', headlights: 'LED', hiddenHandle: false, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["长安"].id, name: "CS75 Plus", slug: "changan-cs75-plus", level: "SUV", priceMin: 10.39, priceMax: 15.19, evType: "燃油", salesVolume2025: 175597, imageUrl: null, fuelType: '92#', fuelConsumption: 6.5, enginePower: 131, engineTorque: 265, length: 4700, width: 1865, height: 1710, wheelbase: 2710, weight: 1620, seats: 5, trunkVolume: 620, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', chip: '长安智慧芯', adasLevel: 'L2', screen: '12.3英寸', ota: true, carPlay: true, sunroof: '全景天窗', wheels: '19英寸', headlights: 'LED', hiddenHandle: false, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["本田"].id, name: "CR-V", slug: "honda-cr-v", level: "SUV", priceMin: 18.59, priceMax: 26.39, evType: "燃油", salesVolume2025: 171207, imageUrl: null, fuelType: '92#', fuelConsumption: 7.3, enginePower: 142, engineTorque: 243, length: 4703, width: 1866, height: 1680, wheelbase: 2701, weight: 1640, seats: 5, trunkVolume: 520, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', adasLevel: 'L2', screen: '10.1英寸', ota: false, carPlay: true, sunroof: '全景天窗', wheels: '18英寸', headlights: 'LED', hiddenHandle: false, electricTail: true, seatMaterial: '真皮', seatVentHeat: '仅加热', steeringHeat: false, airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: false, wirelessCharge: true, keyless: true, acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["理想"].id, name: "L6", slug: "lixiang-l6", level: "SUV", priceMin: 24.98, priceMax: 27.98, evType: "增程", salesVolume2025: 166516, imageUrl: null, motorPower: 200, motorTorque: 400, batteryCapacity: 36.8, batteryType: '磷酸铁锂', rangeCLTC: 182, acceleration: 5.4, topSpeed: 180, length: 4925, width: 1960, height: 1735, wheelbase: 2920, weight: 2230, seats: 5, trunkVolume: 680, driveMode: '四驱', suspensionF: '双叉臂', suspensionR: '多连杆', chip: '高通8295', adasLevel: 'L2+', screen: '双15.7英寸', ota: true, carPlay: false, chargeFast: 20, chargeSlow: 6, chargePower: 75, voltage: '400V', sunroof: '全景天窗', wheels: '20英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 9, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '三区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: true, nop: '高速NOA' } });
  await prisma.model.create({ data: { brandId: b["小米"].id, name: "YU7", slug: "xiaomi-yu7", level: "SUV", priceMin: 25.98, priceMax: 33.98, evType: "纯电", salesVolume2025: 153673, imageUrl: null, motorType: '永磁同步', motorPower: 240, motorTorque: 480, batteryCapacity: 94.3, batteryType: '三元锂', rangeCLTC: 770, acceleration: 4.8, topSpeed: 220, length: 4999, width: 1996, height: 1600, wheelbase: 3000, weight: 2280, seats: 5, trunkVolume: 680, driveMode: '四驱', suspensionF: '双叉臂', suspensionR: '多连杆', chip: '骁龙8295', adasLevel: 'L2+', screen: '16.1英寸', ota: true, carPlay: true, chargeFast: 12, chargeSlow: 8, chargePower: 260, voltage: '800V', sunroof: '全景天窗', wheels: '20英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 9, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '三区自动', airPurifier: true, wirelessCharge: true, hud: 'AR-HUD', keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: true, nop: '城市NOA' } });
  await prisma.model.create({ data: { brandId: b["问界"].id, name: "M8", slug: "aito-m8", level: "SUV", priceMin: 36.98, priceMax: 46.98, evType: "增程", salesVolume2025: 150420, imageUrl: null, motorPower: 200, motorTorque: 420, batteryCapacity: 40, batteryType: '三元锂', rangeCLTC: 200, acceleration: 5.2, topSpeed: 190, length: 5190, width: 1999, height: 1795, wheelbase: 3100, weight: 2680, seats: 6, trunkVolume: 410, driveMode: '四驱', suspensionF: '双叉臂', suspensionR: '多连杆', chip: '华为M9', adasLevel: 'L2+', screen: '15.6英寸+12.3英寸', ota: true, carPlay: false, chargeFast: 20, chargeSlow: 8, chargePower: 90, voltage: '400V', sunroof: '全景天窗', wheels: '21英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', rearScreen: '后排娱乐屏', airbags: 9, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '三区自动', airPurifier: true, wirelessCharge: true, hud: 'AR-HUD', keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '记忆泊车', remotePark: true, nop: '城市NOA' } });
  await prisma.model.create({ data: { brandId: b["哈弗"].id, name: "大狗", slug: "haval-dargo", level: "SUV", priceMin: 12.39, priceMax: 16.79, evType: "燃油", salesVolume2025: 149708, imageUrl: null, fuelType: '92#', fuelConsumption: 7.8, enginePower: 124, engineTorque: 285, length: 4620, width: 1890, height: 1780, wheelbase: 2738, weight: 1670, seats: 5, trunkVolume: 520, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', adasLevel: 'L2', screen: '12.3英寸', ota: true, carPlay: true, sunroof: '全景天窗', wheels: '19英寸', headlights: 'LED', hiddenHandle: false, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "汉EV", slug: "byd-han-ev", level: "轿车", priceMin: 20.98, priceMax: 32.98, evType: "纯电", salesVolume2025: 47700, imageUrl: null, motorType: '永磁同步', motorPower: 180, motorTorque: 350, batteryCapacity: 85.4, batteryType: '磷酸铁锂', rangeCLTC: 715, acceleration: 3.9, topSpeed: 185, length: 4995, width: 1910, height: 1495, wheelbase: 2920, weight: 2220, seats: 5, trunkVolume: 410, driveMode: '四驱', suspensionF: '麦弗逊', suspensionR: '多连杆', chip: '地平线征程3', adasLevel: 'L2+', screen: '15.6英寸', ota: true, carPlay: true, chargeFast: 25, chargeSlow: 8.5, chargePower: 120, voltage: '800V', sunroof: '全景天窗', wheels: '19英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 11, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, hud: 'W-HUD', keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: false, nop: '高速NOA' } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "海豹", slug: "byd-seal", level: "轿车", priceMin: 18.98, priceMax: 28.98, evType: "纯电", salesVolume2025: 42500, imageUrl: null, motorType: '永磁同步', motorPower: 170, motorTorque: 330, batteryCapacity: 82.5, batteryType: '磷酸铁锂', rangeCLTC: 700, acceleration: 3.8, topSpeed: 180, length: 4800, width: 1875, height: 1460, wheelbase: 2920, weight: 2085, seats: 5, trunkVolume: 400, driveMode: '后驱', suspensionF: '双叉臂', suspensionR: '多连杆', chip: '地平线征程3', adasLevel: 'L2+', screen: '15.6英寸', ota: true, carPlay: true, chargeFast: 26, chargeSlow: 8, chargePower: 110, voltage: '800V', sunroof: '全景天窗', wheels: '19英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 9, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, hud: 'W-HUD', keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: false, nop: '高速NOA' } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "唐DM-i", slug: "byd-tang-dmi", level: "SUV", priceMin: 20.58, priceMax: 30.58, evType: "插混", salesVolume2025: 65000, imageUrl: null, motorPower: 160, motorTorque: 325, batteryCapacity: 21.5, batteryType: '磷酸铁锂', rangeCLTC: 112, fuelConsumption: 5.5, enginePower: 102, engineTorque: 231, length: 4900, width: 1950, height: 1725, wheelbase: 2820, weight: 2130, seats: 7, trunkVolume: 235, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', adasLevel: 'L2', screen: '15.6英寸', ota: true, carPlay: true, voltage: '400V', sunroof: '全景天窗', wheels: '20英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 9, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '三区自动', airPurifier: true, wirelessCharge: true, hud: 'W-HUD', keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: false } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "海豚", slug: "byd-dolphin", level: "轿车", priceMin: 10.28, priceMax: 13.98, evType: "纯电", salesVolume2025: 160500, imageUrl: null, motorType: '永磁同步', motorPower: 130, motorTorque: 290, batteryCapacity: 44.9, batteryType: '磷酸铁锂', rangeCLTC: 420, topSpeed: 160, length: 4290, width: 1770, height: 1570, wheelbase: 2700, weight: 1450, seats: 5, trunkVolume: 360, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '扭力梁', adasLevel: 'L2', screen: '12.8英寸', ota: true, carPlay: true, chargeSlow: 7, voltage: '400V', sunroof: '全景天窗', wheels: '16英寸', headlights: 'LED', hiddenHandle: false, electricTail: false, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: false, acType: '自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["蔚来"].id, name: "ET5", slug: "nio-et5", level: "轿车", priceMin: 29.8, priceMax: 35.6, evType: "纯电", salesVolume2025: 38000, imageUrl: null, motorType: '永磁同步', motorPower: 210, motorTorque: 420, batteryCapacity: 75, batteryType: '三元锂', rangeCLTC: 560, acceleration: 4.3, topSpeed: 200, length: 4790, width: 1960, height: 1499, wheelbase: 2888, weight: 2120, seats: 5, trunkVolume: 386, driveMode: '四驱', suspensionF: '五连杆', suspensionR: '五连杆', chip: '高通8155', adasLevel: 'L2+', screen: '12.8英寸', ota: true, carPlay: true, chargeFast: 20, chargeSlow: 11, chargePower: 120, voltage: '400V', sunroof: '全景天窗', wheels: '19英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: '真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 9, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, hud: 'AR-HUD', keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: true, nop: '城市NOA' } });
  await prisma.model.create({ data: { brandId: b["蔚来"].id, name: "ES6", slug: "nio-es6", level: "SUV", priceMin: 33.8, priceMax: 39.6, evType: "纯电", salesVolume2025: 43900, imageUrl: null, motorType: '永磁同步', motorPower: 210, motorTorque: 420, batteryCapacity: 75, batteryType: '三元锂', rangeCLTC: 490, acceleration: 4.5, topSpeed: 200, length: 4854, width: 1995, height: 1703, wheelbase: 2915, weight: 2240, seats: 5, trunkVolume: 570, driveMode: '四驱', suspensionF: '五连杆', suspensionR: '五连杆', chip: '高通8155', adasLevel: 'L2+', screen: '12.8英寸', ota: true, carPlay: true, chargeFast: 20, chargeSlow: 11, chargePower: 120, voltage: '400V', sunroof: '全景天窗', wheels: '20英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: '真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 9, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '三区自动', airPurifier: true, wirelessCharge: true, hud: 'AR-HUD', keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: true, nop: '城市NOA' } });
  await prisma.model.create({ data: { brandId: b["小鹏"].id, name: "G6", slug: "xpeng-g6", level: "SUV", priceMin: 20.99, priceMax: 27.99, evType: "纯电", salesVolume2025: 47400, imageUrl: null, motorType: '永磁同步', motorPower: 218, motorTorque: 440, batteryCapacity: 87.5, batteryType: '三元锂', rangeCLTC: 755, acceleration: 5.9, topSpeed: 202, length: 4753, width: 1920, height: 1650, wheelbase: 2890, weight: 2030, seats: 5, trunkVolume: 571, driveMode: '四驱', suspensionF: '双叉臂', suspensionR: '五连杆', chip: '高通8155', adasLevel: 'L2+', screen: '14.96英寸', ota: true, carPlay: false, chargeFast: 20, chargeSlow: 8.5, chargePower: 280, voltage: '800V', sunroof: '全景天窗', wheels: '20英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: true, nop: '城市NOA' } });
  await prisma.model.create({ data: { brandId: b["小鹏"].id, name: "P7i", slug: "xpeng-p7i", level: "轿车", priceMin: 22.39, priceMax: 33.99, evType: "纯电", salesVolume2025: 45000, imageUrl: null, motorType: '永磁同步', motorPower: 203, motorTorque: 440, batteryCapacity: 86.2, batteryType: '三元锂', rangeCLTC: 702, acceleration: 4.1, topSpeed: 200, length: 4888, width: 1896, height: 1450, wheelbase: 2998, weight: 2030, seats: 5, trunkVolume: 440, driveMode: '后驱', suspensionF: '双叉臂', suspensionR: '五连杆', chip: '高通8155', adasLevel: 'L2+', screen: '14.96英寸', ota: true, carPlay: false, chargeFast: 25, chargeSlow: 8.5, chargePower: 180, voltage: '800V', sunroof: '全景天窗', wheels: '19英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 8, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: true, nop: '城市NOA' } });
  await prisma.model.create({ data: { brandId: b["小鹏"].id, name: "MONA M03", slug: "xpeng-mona-m03", level: "轿车", priceMin: 11.98, priceMax: 15.98, evType: "纯电", salesVolume2025: 175200, imageUrl: null, motorType: '永磁同步', motorPower: 140, motorTorque: 310, batteryCapacity: 51.8, batteryType: '磷酸铁锂', rangeCLTC: 515, topSpeed: 155, length: 4780, width: 1896, height: 1445, wheelbase: 2815, weight: 1690, seats: 5, trunkVolume: 621, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '扭力梁', chip: '高通8155', adasLevel: 'L2+', screen: '15.6英寸', ota: true, carPlay: true, chargeFast: 25, chargeSlow: 7, chargePower: 70, voltage: '400V', sunroof: '全景天窗', wheels: '18英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["理想"].id, name: "L7", slug: "lixiang-l7", level: "SUV", priceMin: 31.98, priceMax: 37.98, evType: "增程", salesVolume2025: 52000, imageUrl: null, motorPower: 200, motorTorque: 400, batteryCapacity: 39.2, batteryType: '三元锂', rangeCLTC: 170, acceleration: 5.3, topSpeed: 180, length: 5050, width: 1995, height: 1750, wheelbase: 3005, weight: 2340, seats: 5, trunkVolume: 773, driveMode: '四驱', suspensionF: '双叉臂', suspensionR: '多连杆', chip: '高通8295', adasLevel: 'L2+', screen: '双15.7英寸', ota: true, carPlay: false, chargeFast: 20, chargeSlow: 6, chargePower: 75, voltage: '400V', sunroof: '全景天窗', wheels: '20英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', rearScreen: '后排娱乐屏', airbags: 9, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '三区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: true, nop: '高速NOA' } });
  await prisma.model.create({ data: { brandId: b["理想"].id, name: "L9", slug: "lixiang-l9", level: "SUV", priceMin: 42.98, priceMax: 45.98, evType: "增程", salesVolume2025: 35000, imageUrl: null, motorPower: 200, motorTorque: 400, batteryCapacity: 44.5, batteryType: '三元锂', rangeCLTC: 190, acceleration: 5.3, topSpeed: 180, length: 5218, width: 1998, height: 1800, wheelbase: 3105, weight: 2520, seats: 6, trunkVolume: 332, driveMode: '四驱', suspensionF: '双叉臂', suspensionR: '多连杆', chip: '高通8295', adasLevel: 'L2+', screen: '双15.7英寸+后排娱乐屏', ota: true, carPlay: false, chargeFast: 20, chargeSlow: 6, chargePower: 75, voltage: '400V', sunroof: '全景天窗', wheels: '21英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', rearScreen: '后排娱乐屏', airbags: 10, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '四区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '记忆泊车', remotePark: true, nop: '高速NOA' } });
  await prisma.model.create({ data: { brandId: b["极氪"].id, name: "001", slug: "zeekr-001", level: "轿车", priceMin: 26.9, priceMax: 35.4, evType: "纯电", salesVolume2025: 38000, imageUrl: null, motorType: '永磁同步', motorPower: 200, motorTorque: 384, batteryCapacity: 100.01, batteryType: '三元锂', rangeCLTC: 741, acceleration: 3.8, topSpeed: 240, length: 4977, width: 1999, height: 1545, wheelbase: 3005, weight: 2390, seats: 5, trunkVolume: 2144, driveMode: '四驱', suspensionF: '双叉臂', suspensionR: '多连杆', chip: '高通8295', adasLevel: 'L2+', screen: '15.05英寸', ota: true, carPlay: true, chargeFast: 15, chargeSlow: 9, chargePower: 360, voltage: '800V', sunroof: '全景天窗', wheels: '21英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 8, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, hud: 'AR-HUD', keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: true, nop: '高速NOA' } });
  await prisma.model.create({ data: { brandId: b["极氪"].id, name: "007", slug: "zeekr-007", level: "轿车", priceMin: 20.99, priceMax: 29.99, evType: "纯电", salesVolume2025: 34000, imageUrl: null, motorType: '永磁同步', motorPower: 210, motorTorque: 440, batteryCapacity: 75, batteryType: '磷酸铁锂', rangeCLTC: 688, acceleration: 4.5, topSpeed: 210, length: 4880, width: 1900, height: 1450, wheelbase: 2928, weight: 2070, seats: 5, trunkVolume: 462, driveMode: '后驱', suspensionF: '双叉臂', suspensionR: '多连杆', chip: '高通8295', adasLevel: 'L2+', screen: '15.05英寸', ota: true, carPlay: true, chargeFast: 10, chargeSlow: 8, chargePower: 360, voltage: '800V', sunroof: '全景天窗', wheels: '19英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 8, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, hud: 'AR-HUD', keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: true, nop: '高速NOA' } });
  await prisma.model.create({ data: { brandId: b["阿维塔"].id, name: "11", slug: "avatr-11", level: "SUV", priceMin: 31.99, priceMax: 39.99, evType: "纯电", salesVolume2025: 18000, imageUrl: null, motorType: '永磁同步', motorPower: 230, motorTorque: 470, batteryCapacity: 90.38, batteryType: '三元锂', rangeCLTC: 630, acceleration: 4.2, topSpeed: 200, length: 4880, width: 1970, height: 1601, wheelbase: 2975, weight: 2300, seats: 5, trunkVolume: 480, driveMode: '四驱', suspensionF: '双叉臂', suspensionR: '五连杆', chip: '华为MDC', adasLevel: 'L2+', screen: '15.6英寸', ota: true, carPlay: true, chargeFast: 15, chargeSlow: 11, chargePower: 240, voltage: '800V', sunroof: '全景天窗', wheels: '21英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 8, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: true, nop: '城市NOA' } });
  await prisma.model.create({ data: { brandId: b["阿维塔"].id, name: "12", slug: "avatr-12", level: "轿车", priceMin: 30.08, priceMax: 40.08, evType: "纯电", salesVolume2025: 15000, imageUrl: null, motorType: '永磁同步', motorPower: 230, motorTorque: 470, batteryCapacity: 94.53, batteryType: '三元锂', rangeCLTC: 700, acceleration: 3.9, topSpeed: 210, length: 5020, width: 1999, height: 1460, wheelbase: 3020, weight: 2360, seats: 5, trunkVolume: 453, driveMode: '四驱', suspensionF: '双叉臂', suspensionR: '五连杆', chip: '华为MDC', adasLevel: 'L2+', screen: '35.4英寸4K远端屏', ota: true, carPlay: true, chargeFast: 15, chargeSlow: 11, chargePower: 240, voltage: '800V', sunroof: '全景天窗', wheels: '20英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 8, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, hud: 'AR-HUD', keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: true, nop: '城市NOA' } });
  await prisma.model.create({ data: { brandId: b["大众"].id, name: "ID.4 CROZZ", slug: "vw-id4-crozz", level: "SUV", priceMin: 19.39, priceMax: 29.39, evType: "纯电", salesVolume2025: 20513, imageUrl: null, motorType: '永磁同步', motorPower: 150, motorTorque: 310, batteryCapacity: 84.8, batteryType: '三元锂', rangeCLTC: 550, topSpeed: 160, length: 4592, width: 1852, height: 1629, wheelbase: 2765, weight: 1970, seats: 5, trunkVolume: 512, driveMode: '后驱', suspensionF: '麦弗逊', suspensionR: '五连杆', adasLevel: 'L2', screen: '12英寸', ota: true, carPlay: true, chargeFast: 30, chargeSlow: 8, chargePower: 100, voltage: '400V', sunroof: '全景天窗', wheels: '20英寸', headlights: '矩阵LED', hiddenHandle: false, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, ambientLight: '多色', airbags: 7, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: false } });
  await prisma.model.create({ data: { brandId: b["大众"].id, name: "帕萨特", slug: "vw-passat", level: "轿车", priceMin: 18.19, priceMax: 25.29, evType: "燃油", salesVolume2025: 85000, imageUrl: null, fuelType: '95#', fuelConsumption: 6.3, enginePower: 137, engineTorque: 320, length: 4948, width: 1836, height: 1469, wheelbase: 2871, weight: 1600, seats: 5, trunkVolume: 521, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', adasLevel: 'L2', screen: '9.2英寸', ota: false, carPlay: true, sunroof: '全景天窗', wheels: '18英寸', headlights: '矩阵LED', hiddenHandle: false, electricTail: true, seatMaterial: '真皮', seatVentHeat: '仅加热', steeringHeat: true, ambientLight: '多色', airbags: 9, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '三区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: false } });
  await prisma.model.create({ data: { brandId: b["丰田"].id, name: "凯美瑞", slug: "toyota-camry", level: "轿车", priceMin: 17.18, priceMax: 26.88, evType: "燃油", salesVolume2025: 95000, imageUrl: null, fuelType: '92#', fuelConsumption: 5.7, enginePower: 131, engineTorque: 221, length: 4885, width: 1840, height: 1455, wheelbase: 2825, weight: 1555, seats: 5, trunkVolume: 493, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '双叉臂', adasLevel: 'L2', screen: '12.3英寸', ota: false, carPlay: true, sunroof: '单天窗', wheels: '17英寸', headlights: 'LED', hiddenHandle: false, electricTail: false, seatMaterial: '真皮', seatVentHeat: '仅加热', steeringHeat: false, airbags: 10, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: false, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["宝马"].id, name: "i3", slug: "bmw-i3", level: "轿车", priceMin: 35.39, priceMax: 41.39, evType: "纯电", salesVolume2025: 22800, imageUrl: null, motorType: '永磁同步', motorPower: 210, motorTorque: 400, batteryCapacity: 70.27, batteryType: '三元锂', rangeCLTC: 526, acceleration: 6.2, topSpeed: 180, length: 4872, width: 1846, height: 1481, wheelbase: 2966, weight: 2020, seats: 5, trunkVolume: 410, driveMode: '后驱', suspensionF: '双叉臂', suspensionR: '多连杆', chip: '高通8155', adasLevel: 'L2', screen: '14.9英寸', ota: true, carPlay: true, chargeFast: 35, chargeSlow: 7.5, chargePower: 110, voltage: '400V', sunroof: '全景天窗', wheels: '19英寸', headlights: '矩阵LED', hiddenHandle: false, electricTail: true, seatMaterial: '真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 8, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, hud: 'W-HUD', keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: false } });
  await prisma.model.create({ data: { brandId: b["宝马"].id, name: "3系", slug: "bmw-3-series", level: "轿车", priceMin: 29.99, priceMax: 39.99, evType: "燃油", salesVolume2025: 78000, imageUrl: null, fuelType: '95#', fuelConsumption: 6.5, enginePower: 135, engineTorque: 300, length: 4713, width: 1827, height: 1455, wheelbase: 2851, weight: 1610, seats: 5, trunkVolume: 480, driveMode: '后驱', suspensionF: '双叉臂', suspensionR: '多连杆', adasLevel: 'L2', screen: '12.3+14.9英寸', ota: true, carPlay: true, sunroof: '全景天窗', wheels: '18英寸', headlights: '矩阵LED', hiddenHandle: false, electricTail: true, seatMaterial: '真皮', seatVentHeat: '仅加热', steeringHeat: true, ambientLight: '多色', airbags: 8, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, hud: 'W-HUD', keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: false } });
  await prisma.model.create({ data: { brandId: b["零跑"].id, name: "C10", slug: "leapmotor-c10", level: "SUV", priceMin: 12.88, priceMax: 16.88, evType: "纯电", salesVolume2025: 100900, imageUrl: null, motorType: '永磁同步', motorPower: 170, motorTorque: 320, batteryCapacity: 69.9, batteryType: '磷酸铁锂', rangeCLTC: 530, topSpeed: 170, length: 4739, width: 1900, height: 1680, wheelbase: 2825, weight: 1910, seats: 5, trunkVolume: 435, driveMode: '后驱', suspensionF: '麦弗逊', suspensionR: '多连杆', chip: '高通8295', adasLevel: 'L2', screen: '14.6英寸', ota: true, carPlay: true, chargeFast: 30, chargeSlow: 7, chargePower: 80, voltage: '400V', sunroof: '全景天窗', wheels: '18英寸', headlights: 'LED', hiddenHandle: true, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["零跑"].id, name: "C11", slug: "leapmotor-c11", level: "SUV", priceMin: 14.58, priceMax: 20.58, evType: "纯电", salesVolume2025: 62000, imageUrl: null, motorType: '永磁同步', motorPower: 200, motorTorque: 360, batteryCapacity: 76.6, batteryType: '磷酸铁锂', rangeCLTC: 580, topSpeed: 170, length: 4780, width: 1905, height: 1675, wheelbase: 2930, weight: 2050, seats: 5, trunkVolume: 500, driveMode: '后驱', suspensionF: '麦弗逊', suspensionR: '五连杆', chip: '高通8295', adasLevel: 'L2+', screen: '14.6英寸', ota: true, carPlay: true, chargeFast: 30, chargeSlow: 7, chargePower: 80, voltage: '400V', sunroof: '全景天窗', wheels: '19英寸', headlights: 'LED', hiddenHandle: true, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: true, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: false } });
  await prisma.model.create({ data: { brandId: b["问界"].id, name: "M9", slug: "aito-m9", level: "SUV", priceMin: 46.98, priceMax: 56.98, evType: "增程", salesVolume2025: 128000, imageUrl: null, motorPower: 230, motorTorque: 450, batteryCapacity: 52, batteryType: '三元锂', rangeCLTC: 220, acceleration: 4.3, topSpeed: 200, length: 5230, width: 1999, height: 1800, wheelbase: 3110, weight: 2850, seats: 6, trunkVolume: 340, driveMode: '四驱', suspensionF: '双叉臂', suspensionR: '多连杆', chip: '华为M9', adasLevel: 'L2+', screen: '16英寸+后排投影', ota: true, carPlay: false, chargeFast: 20, chargeSlow: 8, chargePower: 100, voltage: '800V', sunroof: '全景天窗', wheels: '21英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', rearScreen: '后排投影', airbags: 12, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '四区自动', airPurifier: true, wirelessCharge: true, hud: 'AR-HUD', keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '记忆泊车', remotePark: true, nop: '城市NOA' } });
  await prisma.model.create({ data: { brandId: b["问界"].id, name: "M7", slug: "aito-m7", level: "SUV", priceMin: 24.98, priceMax: 32.98, evType: "增程", salesVolume2025: 109600, imageUrl: null, motorPower: 200, motorTorque: 400, batteryCapacity: 40, batteryType: '三元锂', rangeCLTC: 200, acceleration: 4.8, topSpeed: 190, length: 5020, width: 1945, height: 1760, wheelbase: 2820, weight: 2450, seats: 6, trunkVolume: 520, driveMode: '四驱', suspensionF: '麦弗逊', suspensionR: '多连杆', chip: '华为M9', adasLevel: 'L2+', screen: '15.6英寸', ota: true, carPlay: false, chargeFast: 20, chargeSlow: 8, chargePower: 90, voltage: '400V', sunroof: '全景天窗', wheels: '20英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 9, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '三区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: true, nop: '城市NOA' } });
  await prisma.model.create({ data: { brandId: b["深蓝"].id, name: "S07", slug: "deepal-s07", level: "SUV", priceMin: 14.99, priceMax: 20.79, evType: "增程", salesVolume2025: 72000, imageUrl: null, motorPower: 160, motorTorque: 320, batteryCapacity: 31.73, batteryType: '磷酸铁锂', rangeCLTC: 121, acceleration: 7.5, topSpeed: 180, length: 4750, width: 1930, height: 1625, wheelbase: 2900, weight: 1930, seats: 5, trunkVolume: 520, driveMode: '后驱', suspensionF: '麦弗逊', suspensionR: '多连杆', chip: '高通8155', adasLevel: 'L2+', screen: '14.6英寸', ota: true, carPlay: true, chargeFast: 25, chargeSlow: 7, chargePower: 70, voltage: '400V', sunroof: '全景天窗', wheels: '19英寸', headlights: 'LED', hiddenHandle: true, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["腾势"].id, name: "D9", slug: "denza-d9", level: "MPV", priceMin: 33.58, priceMax: 46.58, evType: "插混", salesVolume2025: 82100, imageUrl: null, motorPower: 170, motorTorque: 340, batteryCapacity: 39.9, batteryType: '磷酸铁锂', rangeCLTC: 180, fuelConsumption: 5.5, enginePower: 102, engineTorque: 231, length: 5250, width: 1960, height: 1920, wheelbase: 3110, weight: 2620, seats: 7, trunkVolume: 410, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', chip: '高通8155', adasLevel: 'L2+', screen: '15.6英寸', ota: true, carPlay: true, chargeFast: 25, chargeSlow: 8, chargePower: 80, voltage: '400V', sunroof: '全景天窗', wheels: '18英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', rearScreen: '后排娱乐屏', airbags: 9, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '四区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: false } });
  await prisma.model.create({ data: { brandId: b["方程豹"].id, name: "豹5", slug: "fangchengbao-leopard-5", level: "SUV", priceMin: 23.98, priceMax: 30.28, evType: "插混", salesVolume2025: 51900, imageUrl: null, motorPower: 200, motorTorque: 420, batteryCapacity: 31.8, batteryType: '磷酸铁锂', rangeCLTC: 100, fuelConsumption: 5.5, enginePower: 102, engineTorque: 231, length: 4890, width: 1970, height: 1920, wheelbase: 2800, weight: 2580, seats: 5, trunkVolume: 400, driveMode: '四驱', suspensionF: '双叉臂', suspensionR: '多连杆', chip: '高通8155', adasLevel: 'L2+', screen: '15.6英寸', ota: true, carPlay: true, chargeFast: 25, chargeSlow: 8, chargePower: 100, voltage: '400V', sunroof: '全景天窗', wheels: '18英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '三区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: false } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "元Plus", slug: "byd-yuan-plus", level: "SUV", priceMin: 13.28, priceMax: 15.98, evType: "纯电", salesVolume2025: 135446, imageUrl: null, motorType: '永磁同步', motorPower: 150, motorTorque: 310, batteryCapacity: 60.48, batteryType: '磷酸铁锂', rangeCLTC: 510, topSpeed: 160, length: 4455, width: 1875, height: 1615, wheelbase: 2720, weight: 1690, seats: 5, trunkVolume: 434, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', adasLevel: 'L2', screen: '12.8英寸', ota: true, carPlay: true, chargeSlow: 7, voltage: '400V', sunroof: '全景天窗', wheels: '17英寸', headlights: 'LED', hiddenHandle: false, electricTail: false, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["吉利银河"].id, name: "E5", slug: "geely-galaxy-e5", level: "SUV", priceMin: 11.28, priceMax: 15.58, evType: "纯电", salesVolume2025: 120978, imageUrl: null, motorType: '永磁同步', motorPower: 160, motorTorque: 320, batteryCapacity: 60.22, batteryType: '磷酸铁锂', rangeCLTC: 530, topSpeed: 170, length: 4615, width: 1901, height: 1670, wheelbase: 2750, weight: 1770, seats: 5, trunkVolume: 510, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', chip: '吉利龙鹰', adasLevel: 'L2', screen: '14.6英寸', ota: true, carPlay: true, chargeFast: 25, chargeSlow: 7, chargePower: 80, voltage: '400V', sunroof: '全景天窗', wheels: '18英寸', headlights: 'LED', hiddenHandle: true, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["吉利银河"].id, name: "星舰7", slug: "geely-galaxy-starship-7", level: "SUV", priceMin: 10.98, priceMax: 14.98, evType: "插混", salesVolume2025: 102000, imageUrl: null, motorPower: 120, motorTorque: 260, batteryCapacity: 18.3, batteryType: '磷酸铁锂', rangeCLTC: 100, fuelConsumption: 3.8, enginePower: 82, engineTorque: 148, length: 4735, width: 1865, height: 1710, wheelbase: 2760, weight: 1720, seats: 5, trunkVolume: 550, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', chip: '吉利龙鹰', adasLevel: 'L2', screen: '14.6英寸', ota: true, carPlay: true, voltage: '400V', sunroof: '全景天窗', wheels: '18英寸', headlights: 'LED', hiddenHandle: true, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["奇瑞"].id, name: "瑞虎5X", slug: "chery-tiggo-5x", level: "SUV", priceMin: 6.99, priceMax: 10.89, evType: "燃油", salesVolume2025: 90000, imageUrl: null, fuelType: '92#', fuelConsumption: 6.5, enginePower: 85, engineTorque: 143, length: 4358, width: 1830, height: 1670, wheelbase: 2630, weight: 1350, seats: 5, trunkVolume: 370, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '扭力梁', screen: '10.25英寸', ota: false, carPlay: true, sunroof: '单天窗', wheels: '17英寸', headlights: '卤素', hiddenHandle: false, electricTail: false, seatMaterial: '织物', seatVentHeat: '无', steeringHeat: false, airbags: 4, tirePressure: '间接', autoBrake: false, blindSpot: false, acType: '手动', airPurifier: false, wirelessCharge: false, keyless: false, lka: false, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["奇瑞"].id, name: "瑞虎7", slug: "chery-tiggo-7", level: "SUV", priceMin: 8.99, priceMax: 14.59, evType: "燃油", salesVolume2025: 85000, imageUrl: null, fuelType: '92#', fuelConsumption: 6.8, enginePower: 115, engineTorque: 230, length: 4500, width: 1842, height: 1746, wheelbase: 2670, weight: 1500, seats: 5, trunkVolume: 470, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', adasLevel: 'L2', screen: '12.3英寸', ota: true, carPlay: true, sunroof: '全景天窗', wheels: '18英寸', headlights: 'LED', hiddenHandle: false, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: false, acType: '自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["长安"].id, name: "Lumin", slug: "changan-lumin", level: "轿车", priceMin: 4.99, priceMax: 6.99, evType: "纯电", salesVolume2025: 159300, imageUrl: null, motorType: '永磁同步', motorPower: 30, motorTorque: 79, batteryCapacity: 12.92, batteryType: '磷酸铁锂', rangeCLTC: 155, topSpeed: 101, length: 3273, width: 1700, height: 1545, wheelbase: 1980, weight: 860, seats: 4, trunkVolume: 120, driveMode: '后驱', suspensionF: '麦弗逊', suspensionR: '扭力梁', screen: '7英寸', ota: false, carPlay: false, chargeSlow: 5, voltage: '400V', sunroof: '无', wheels: '14英寸', headlights: '卤素', hiddenHandle: false, electricTail: false, seatMaterial: '织物', seatVentHeat: '无', steeringHeat: false, airbags: 2, autoBrake: false, blindSpot: false, acType: '手动', airPurifier: false, wirelessCharge: false, keyless: false, lka: false, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["领克"].id, name: "08 EM-P", slug: "lynk-co-08-emp", level: "SUV", priceMin: 19.58, priceMax: 26.98, evType: "插混", salesVolume2025: 55000, imageUrl: null, motorPower: 200, motorTorque: 380, batteryCapacity: 39.8, batteryType: '三元锂', rangeCLTC: 205, acceleration: 5.5, topSpeed: 190, length: 4820, width: 1915, height: 1685, wheelbase: 2845, weight: 2150, seats: 5, trunkVolume: 545, driveMode: '四驱', suspensionF: '麦弗逊', suspensionR: '多连杆', chip: '高通8155', adasLevel: 'L2+', screen: '15.4英寸', ota: true, carPlay: true, chargeFast: 28, chargeSlow: 7, chargePower: 70, voltage: '400V', sunroof: '全景天窗', wheels: '20英寸', headlights: '矩阵LED', hiddenHandle: true, electricTail: true, seatMaterial: 'Nappa真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 8, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, hud: 'AR-HUD', keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: true, nop: '高速NOA' } });
  await prisma.model.create({ data: { brandId: b["红旗"].id, name: "HS5", slug: "hongqi-hs5", level: "SUV", priceMin: 18.38, priceMax: 24.98, evType: "燃油", salesVolume2025: 60000, imageUrl: null, fuelType: '95#', fuelConsumption: 7.9, enginePower: 165, engineTorque: 340, length: 4785, width: 1905, height: 1700, wheelbase: 2870, weight: 1800, seats: 5, trunkVolume: 560, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', adasLevel: 'L2', screen: '12.3英寸双联屏', ota: true, carPlay: true, sunroof: '全景天窗', wheels: '19英寸', headlights: 'LED', hiddenHandle: false, electricTail: true, seatMaterial: '真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 7, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["广汽埃安"].id, name: "Aion S", slug: "gac-aion-s", level: "轿车", priceMin: 13.98, priceMax: 18.98, evType: "纯电", salesVolume2025: 55000, imageUrl: null, motorType: '永磁同步', motorPower: 150, motorTorque: 310, batteryCapacity: 58.3, batteryType: '磷酸铁锂', rangeCLTC: 510, topSpeed: 165, length: 4800, width: 1880, height: 1545, wheelbase: 2750, weight: 1720, seats: 5, trunkVolume: 453, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '扭力梁', adasLevel: 'L2', screen: '14.6英寸', ota: true, carPlay: true, chargeSlow: 7.5, voltage: '400V', sunroof: '全景天窗', wheels: '17英寸', headlights: 'LED', hiddenHandle: true, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["广汽埃安"].id, name: "Aion Y", slug: "gac-aion-y", level: "SUV", priceMin: 11.98, priceMax: 16.58, evType: "纯电", salesVolume2025: 48000, imageUrl: null, motorType: '永磁同步', motorPower: 150, motorTorque: 310, batteryCapacity: 61.7, batteryType: '磷酸铁锂', rangeCLTC: 510, topSpeed: 150, length: 4535, width: 1870, height: 1650, wheelbase: 2750, weight: 1700, seats: 5, trunkVolume: 380, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '扭力梁', adasLevel: 'L2', screen: '14.6英寸', ota: true, carPlay: true, chargeSlow: 7.5, voltage: '400V', sunroof: '全景天窗', wheels: '18英寸', headlights: 'LED', hiddenHandle: false, electricTail: false, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: false, acType: '自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["奔驰"].id, name: "GLC", slug: "benz-glc", level: "SUV", priceMin: 42.78, priceMax: 53.88, evType: "燃油", salesVolume2025: 130610, imageUrl: null, fuelType: '95#', fuelConsumption: 8.1, enginePower: 190, engineTorque: 400, length: 4764, width: 1898, height: 1642, wheelbase: 2973, weight: 2010, seats: 5, trunkVolume: 580, driveMode: '四驱', suspensionF: '多连杆', suspensionR: '多连杆', adasLevel: 'L2', screen: '11.9英寸', ota: true, carPlay: true, sunroof: '全景天窗', wheels: '19英寸', headlights: '矩阵LED', hiddenHandle: false, electricTail: true, seatMaterial: '真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 9, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: false } });
  await prisma.model.create({ data: { brandId: b["奥迪"].id, name: "Q5L", slug: "audi-q5l", level: "SUV", priceMin: 39.68, priceMax: 49.88, evType: "燃油", salesVolume2025: 133589, imageUrl: null, fuelType: '95#', fuelConsumption: 7.9, enginePower: 180, engineTorque: 370, length: 4770, width: 1893, height: 1667, wheelbase: 2908, weight: 1890, seats: 5, trunkVolume: 550, driveMode: '四驱', suspensionF: '五连杆', suspensionR: '五连杆', adasLevel: 'L2', screen: '10.1英寸', ota: false, carPlay: true, sunroof: '全景天窗', wheels: '19英寸', headlights: '矩阵LED', hiddenHandle: false, electricTail: true, seatMaterial: '真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 8, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '三区自动', airPurifier: true, wirelessCharge: true, keyless: true, acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: false } });
  await prisma.model.create({ data: { brandId: b["别克"].id, name: "昂科威", slug: "buick-envision", level: "SUV", priceMin: 18.99, priceMax: 26.29, evType: "燃油", salesVolume2025: 129095, imageUrl: null, fuelType: '92#', fuelConsumption: 7.6, enginePower: 169, engineTorque: 350, length: 4822, width: 1883, height: 1695, wheelbase: 2833, weight: 1770, seats: 5, trunkVolume: 400, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', adasLevel: 'L2', screen: '8英寸', ota: false, carPlay: true, sunroof: '全景天窗', wheels: '18英寸', headlights: 'LED', hiddenHandle: false, electricTail: true, seatMaterial: '真皮', seatVentHeat: '仅加热', steeringHeat: true, airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "宋L DM-i", slug: "byd-song-l-dmi", level: "SUV", priceMin: 13.58, priceMax: 18.58, evType: "插混", salesVolume2025: 137120, imageUrl: null, motorPower: 145, motorTorque: 325, batteryCapacity: 18.3, batteryType: '磷酸铁锂', rangeCLTC: 112, fuelConsumption: 3.9, enginePower: 81, engineTorque: 135, length: 4780, width: 1898, height: 1670, wheelbase: 2782, weight: 1860, seats: 5, trunkVolume: 520, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', chip: '地平线征程3', adasLevel: 'L2', screen: '15.6英寸', ota: true, carPlay: true, voltage: '400V', sunroof: '全景天窗', wheels: '19英寸', headlights: 'LED', hiddenHandle: true, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["大众"].id, name: "探岳", slug: "vw-tayron", level: "SUV", priceMin: 18.69, priceMax: 26.69, evType: "燃油", salesVolume2025: 173329, imageUrl: null, fuelType: '95#', fuelConsumption: 7.0, enginePower: 137, engineTorque: 320, length: 4589, width: 1860, height: 1660, wheelbase: 2731, weight: 1720, seats: 5, trunkVolume: 506, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', adasLevel: 'L2', screen: '12英寸', ota: false, carPlay: true, sunroof: '全景天窗', wheels: '19英寸', headlights: '矩阵LED', hiddenHandle: false, electricTail: true, seatMaterial: '真皮', seatVentHeat: '仅加热', steeringHeat: true, ambientLight: '多色', airbags: 7, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["丰田"].id, name: "锋兰达", slug: "toyota-frontlander", level: "SUV", priceMin: 12.58, priceMax: 18.48, evType: "燃油", salesVolume2025: 186575, imageUrl: null, fuelType: '92#', fuelConsumption: 5.8, enginePower: 103, engineTorque: 185, length: 4485, width: 1825, height: 1620, wheelbase: 2640, weight: 1450, seats: 5, trunkVolume: 438, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '扭力梁', adasLevel: 'L2', screen: '10.25英寸', ota: false, carPlay: true, sunroof: '全景天窗', wheels: '17英寸', headlights: 'LED', hiddenHandle: false, electricTail: false, seatMaterial: '仿皮', seatVentHeat: '无', steeringHeat: false, airbags: 7, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '自动', airPurifier: true, wirelessCharge: false, keyless: true, acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["哈弗"].id, name: "H6", slug: "haval-h6", level: "SUV", priceMin: 9.89, priceMax: 15.69, evType: "燃油", salesVolume2025: 82000, imageUrl: null, fuelType: '92#', fuelConsumption: 7.1, enginePower: 124, engineTorque: 285, length: 4645, width: 1890, height: 1710, wheelbase: 2738, weight: 1620, seats: 5, trunkVolume: 560, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', adasLevel: 'L2', screen: '12.3英寸', ota: true, carPlay: true, sunroof: '全景天窗', wheels: '19英寸', headlights: 'LED', hiddenHandle: false, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["捷途"].id, name: "旅行者", slug: "jetour-traveler", level: "SUV", priceMin: 13.99, priceMax: 21.99, evType: "燃油", salesVolume2025: 65000, imageUrl: null, fuelType: '92#', fuelConsumption: 8.5, enginePower: 135, engineTorque: 290, length: 4785, width: 2006, height: 1880, wheelbase: 2800, weight: 1800, seats: 5, trunkVolume: 700, driveMode: '四驱', suspensionF: '麦弗逊', suspensionR: '多连杆', adasLevel: 'L2', screen: '15.6英寸', ota: true, carPlay: true, sunroof: '全景天窗', wheels: '19英寸', headlights: 'LED', hiddenHandle: false, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: true, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "海狮06", slug: "byd-sealion-06", level: "SUV", priceMin: 16.98, priceMax: 23.98, evType: "插混", salesVolume2025: 89800, imageUrl: null, motorPower: 160, motorTorque: 325, batteryCapacity: 21.5, batteryType: '磷酸铁锂', rangeCLTC: 110, fuelConsumption: 4.5, enginePower: 102, engineTorque: 231, length: 4710, width: 1880, height: 1670, wheelbase: 2765, weight: 1850, seats: 5, trunkVolume: 510, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', chip: '地平线征程3', adasLevel: 'L2', screen: '12.8英寸', ota: true, carPlay: true, voltage: '400V', sunroof: '全景天窗', wheels: '19英寸', headlights: 'LED', hiddenHandle: true, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "海豹06 GT", slug: "byd-seal-06-gt", level: "轿车", priceMin: 13.68, priceMax: 17.68, evType: "纯电", salesVolume2025: 47900, imageUrl: null, motorType: '永磁同步', motorPower: 160, motorTorque: 310, batteryCapacity: 59.52, batteryType: '磷酸铁锂', rangeCLTC: 505, acceleration: 7.5, topSpeed: 180, length: 4630, width: 1880, height: 1490, wheelbase: 2820, weight: 1830, seats: 5, trunkVolume: 380, driveMode: '后驱', suspensionF: '麦弗逊', suspensionR: '多连杆', adasLevel: 'L2', screen: '12.8英寸', ota: true, carPlay: true, chargeFast: 25, chargeSlow: 8, chargePower: 70, voltage: '400V', sunroof: '全景天窗', wheels: '17英寸', headlights: 'LED', hiddenHandle: true, electricTail: false, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["吉利银河"].id, name: "L7", slug: "geely-galaxy-l7", level: "SUV", priceMin: 13.57, priceMax: 17.37, evType: "插混", salesVolume2025: 36334, imageUrl: null, motorPower: 107, motorTorque: 228, batteryCapacity: 18.7, batteryType: '磷酸铁锂', rangeCLTC: 90, fuelConsumption: 4.3, enginePower: 82, engineTorque: 148, length: 4705, width: 1905, height: 1700, wheelbase: 2785, weight: 1780, seats: 5, trunkVolume: 530, driveMode: '前驱', suspensionF: '麦弗逊', suspensionR: '多连杆', chip: '吉利龙鹰', adasLevel: 'L2', screen: '13.2英寸', ota: true, carPlay: true, voltage: '400V', sunroof: '全景天窗', wheels: '18英寸', headlights: 'LED', hiddenHandle: false, electricTail: true, seatMaterial: '仿皮', seatVentHeat: '仅加热', steeringHeat: false, ambientLight: '多色', airbags: 6, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, remoteControl: 'APP远程+蓝牙钥匙', acc: '全速ACC', lka: true, remotePark: false } });
  await prisma.model.create({ data: { brandId: b["沃尔沃"].id, name: "XC60", slug: "volvo-xc60", level: "SUV", priceMin: 36.69, priceMax: 47.49, evType: "燃油", salesVolume2025: 45000, imageUrl: null, fuelType: '95#', fuelConsumption: 7.8, enginePower: 184, engineTorque: 350, length: 4688, width: 1902, height: 1658, wheelbase: 2865, weight: 1950, seats: 5, trunkVolume: 505, driveMode: '四驱', suspensionF: '双叉臂', suspensionR: '多连杆', adasLevel: 'L2+', screen: '9英寸', ota: true, carPlay: true, sunroof: '全景天窗', wheels: '19英寸', headlights: '矩阵LED', hiddenHandle: false, electricTail: true, seatMaterial: '真皮', seatVentHeat: '通风+加热', steeringHeat: true, ambientLight: '多色', airbags: 8, tirePressure: '直接', autoBrake: true, blindSpot: true, acType: '双区自动', airPurifier: true, wirelessCharge: true, keyless: true, acc: '全速ACC', lka: true, autoPark: '自动泊车', remotePark: false } });

  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "秦PLUS EV", slug: "byd-qin-plus-ev", level: "轿车", priceMin: 12.98, priceMax: 17.68, evType: "纯电", salesVolume2025: 110400, imageUrl: null, motorType: "永磁同步", motorPower: 100, motorTorque: 180, batteryCapacity: 47.5, batteryType: "磷酸铁锂", rangeCLTC: 420, topSpeed: 130, length: 4765, width: 1837, height: 1495, wheelbase: 2718, weight: 1600, seats: 5, trunkVolume: 500, driveMode: "前驱", suspensionF: "麦弗逊", suspensionR: "扭力梁", adasLevel: "L2", screen: "10.1英寸", ota: true, carPlay: true, chargeSlow: 7, voltage: "400V" } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "驱逐舰05", slug: "byd-destroyer-05", level: "轿车", priceMin: 10.18, priceMax: 15.78, evType: "插混", salesVolume2025: 55000, imageUrl: null, motorPower: 132, motorTorque: 316, batteryCapacity: 8.32, batteryType: "磷酸铁锂", rangeCLTC: 55, fuelConsumption: 3.8, enginePower: 74, engineTorque: 126, length: 4780, width: 1837, height: 1495, wheelbase: 2718, weight: 1540, seats: 5, trunkVolume: 500, driveMode: "前驱", suspensionF: "麦弗逊", suspensionR: "扭力梁", adasLevel: "L2", screen: "12.8英寸", ota: true, carPlay: true, voltage: "400V" } });
  await prisma.model.create({ data: { brandId: b["小鹏"].id, name: "G9", slug: "xpeng-g9", level: "SUV", priceMin: 26.39, priceMax: 41.99, evType: "纯电", salesVolume2025: 20129, imageUrl: null, motorType: "永磁同步", motorPower: 230, motorTorque: 440, batteryCapacity: 98, batteryType: "三元锂", rangeCLTC: 702, acceleration: 3.9, topSpeed: 200, length: 4891, width: 1937, height: 1680, wheelbase: 2998, weight: 2370, seats: 5, trunkVolume: 660, driveMode: "四驱", suspensionF: "双叉臂", suspensionR: "五连杆", chip: "高通8155", adasLevel: "L2+", screen: "14.96英寸", ota: true, carPlay: false, chargeFast: 20, chargeSlow: 8.5, chargePower: 280, voltage: "800V" } });
  await prisma.model.create({ data: { brandId: b["小鹏"].id, name: "X9", slug: "xpeng-x9", level: "MPV", priceMin: 35.98, priceMax: 41.98, evType: "纯电", salesVolume2025: 25000, imageUrl: null, motorType: "永磁同步", motorPower: 235, motorTorque: 450, batteryCapacity: 101.5, batteryType: "三元锂", rangeCLTC: 610, acceleration: 5.7, topSpeed: 200, length: 5293, width: 1988, height: 1785, wheelbase: 3160, weight: 2650, seats: 7, trunkVolume: 720, driveMode: "四驱", suspensionF: "双叉臂", suspensionR: "多连杆", chip: "高通8295", adasLevel: "L2+", screen: "17.3英寸", ota: true, carPlay: true, chargeFast: 15, chargeSlow: 9, chargePower: 280, voltage: "800V" } });
  await prisma.model.create({ data: { brandId: b["岚图"].id, name: "梦想家", slug: "voyah-dreamer", level: "MPV", priceMin: 36.99, priceMax: 46.99, evType: "插混", salesVolume2025: 18000, imageUrl: null, motorPower: 130, motorTorque: 300, batteryCapacity: 25.57, batteryType: "三元锂", rangeCLTC: 82, fuelConsumption: 6.0, enginePower: 102, engineTorque: 231, length: 5315, width: 1985, height: 1810, wheelbase: 3200, weight: 2680, seats: 7, trunkVolume: 500, driveMode: "前驱", suspensionF: "麦弗逊", suspensionR: "多连杆", chip: "高通8155", adasLevel: "L2", screen: "12.3英寸三联屏", ota: true, carPlay: true, chargeFast: 30, chargeSlow: 7, voltage: "400V" } });
  await prisma.model.create({ data: { brandId: b["岚图"].id, name: "FREE", slug: "voyah-free", level: "SUV", priceMin: 22.89, priceMax: 32.89, evType: "增程", salesVolume2025: 12000, imageUrl: null, motorPower: 200, motorTorque: 410, batteryCapacity: 33, batteryType: "三元锂", rangeCLTC: 160, acceleration: 4.5, topSpeed: 200, length: 4905, width: 1950, height: 1645, wheelbase: 2960, weight: 2260, seats: 5, trunkVolume: 560, driveMode: "四驱", suspensionF: "双叉臂", suspensionR: "多连杆", chip: "高通8155", adasLevel: "L2+", screen: "12.3英寸三联屏", ota: true, carPlay: true, chargeFast: 30, chargeSlow: 7, chargePower: 70, voltage: "400V" } });
  await prisma.model.create({ data: { brandId: b["哪吒"].id, name: "S", slug: "nepta-s", level: "轿车", priceMin: 15.98, priceMax: 24.98, evType: "纯电", salesVolume2025: 18000, imageUrl: null, motorType: "永磁同步", motorPower: 170, motorTorque: 310, batteryCapacity: 64.5, batteryType: "三元锂", rangeCLTC: 520, acceleration: 6.9, topSpeed: 185, length: 4980, width: 1980, height: 1450, wheelbase: 2980, weight: 2010, seats: 5, trunkVolume: 400, driveMode: "后驱", suspensionF: "双叉臂", suspensionR: "五连杆", chip: "高通8155", adasLevel: "L2", screen: "17.6英寸", ota: true, carPlay: true, chargeFast: 25, chargeSlow: 8, chargePower: 110, voltage: "400V" } });
  await prisma.model.create({ data: { brandId: b["哪吒"].id, name: "L", slug: "nepta-l", level: "SUV", priceMin: 12.99, priceMax: 17.99, evType: "增程", salesVolume2025: 22000, imageUrl: null, motorPower: 170, motorTorque: 310, batteryCapacity: 30, batteryType: "磷酸铁锂", rangeCLTC: 130, topSpeed: 160, length: 4770, width: 1900, height: 1660, wheelbase: 2810, weight: 1920, seats: 5, trunkVolume: 550, driveMode: "后驱", suspensionF: "麦弗逊", suspensionR: "多连杆", adasLevel: "L2", screen: "15.6英寸", ota: true, carPlay: true, chargeFast: 25, chargeSlow: 7, chargePower: 60, voltage: "400V" } });
  await prisma.model.create({ data: { brandId: b["保时捷"].id, name: "Taycan", slug: "porsche-taycan", level: "轿车", priceMin: 89.8, priceMax: 183.8, evType: "纯电", salesVolume2025: 8500, imageUrl: null, motorType: "永磁同步", motorPower: 460, motorTorque: 850, batteryCapacity: 93.4, batteryType: "三元锂", rangeCLTC: 489, acceleration: 3.2, topSpeed: 260, length: 4963, width: 1966, height: 1378, wheelbase: 2900, weight: 2290, seats: 4, trunkVolume: 407, driveMode: "四驱", suspensionF: "双叉臂", suspensionR: "多连杆", adasLevel: "L2", screen: "16.8英寸", ota: true, carPlay: true, chargeFast: 22.5, chargeSlow: 10, chargePower: 270, voltage: "800V" } });
  await prisma.model.create({ data: { brandId: b["奔驰"].id, name: "C级", slug: "benz-c-class", level: "轿车", priceMin: 32.52, priceMax: 37.42, evType: "燃油", salesVolume2025: 58000, imageUrl: null, fuelType: "95#", fuelConsumption: 7.0, enginePower: 150, engineTorque: 300, length: 4882, width: 1820, height: 1461, wheelbase: 2954, weight: 1640, seats: 5, trunkVolume: 455, driveMode: "后驱", suspensionF: "多连杆", suspensionR: "多连杆", adasLevel: "L2", screen: "11.9英寸", ota: true, carPlay: true } });
  await prisma.model.create({ data: { brandId: b["奔驰"].id, name: "E级", slug: "benz-e-class", level: "轿车", priceMin: 44.72, priceMax: 56.42, evType: "燃油", salesVolume2025: 42000, imageUrl: null, fuelType: "95#", fuelConsumption: 7.8, enginePower: 190, engineTorque: 400, length: 5078, width: 1860, height: 1480, wheelbase: 3079, weight: 1890, seats: 5, trunkVolume: 540, driveMode: "四驱", suspensionF: "多连杆", suspensionR: "多连杆", adasLevel: "L2", screen: "14.4英寸", ota: true, carPlay: true } });
  await prisma.model.create({ data: { brandId: b["奥迪"].id, name: "A4L", slug: "audi-a4l", level: "轿车", priceMin: 30.58, priceMax: 39.68, evType: "燃油", salesVolume2025: 55000, imageUrl: null, fuelType: "95#", fuelConsumption: 6.9, enginePower: 140, engineTorque: 320, length: 4858, width: 1847, height: 1411, wheelbase: 2908, weight: 1650, seats: 5, trunkVolume: 490, driveMode: "前驱", suspensionF: "五连杆", suspensionR: "五连杆", adasLevel: "L2", screen: "12.3英寸", ota: false, carPlay: true } });
  await prisma.model.create({ data: { brandId: b["奥迪"].id, name: "A6L", slug: "audi-a6l", level: "轿车", priceMin: 42.79, priceMax: 65.68, evType: "燃油", salesVolume2025: 38000, imageUrl: null, fuelType: "95#", fuelConsumption: 7.5, enginePower: 180, engineTorque: 370, length: 5050, width: 1886, height: 1475, wheelbase: 3024, weight: 1870, seats: 5, trunkVolume: 530, driveMode: "四驱", suspensionF: "五连杆", suspensionR: "五连杆", adasLevel: "L2", screen: "10.1+12.3英寸", ota: false, carPlay: true } });
  await prisma.model.create({ data: { brandId: b["丰田"].id, name: "卡罗拉", slug: "toyota-corolla", level: "轿车", priceMin: 10.58, priceMax: 15.58, evType: "燃油", salesVolume2025: 82000, imageUrl: null, fuelType: "92#", fuelConsumption: 5.1, enginePower: 85, engineTorque: 185, length: 4635, width: 1780, height: 1455, wheelbase: 2700, weight: 1350, seats: 5, trunkVolume: 470, driveMode: "前驱", suspensionF: "麦弗逊", suspensionR: "扭力梁", adasLevel: "L2", screen: "9英寸", ota: false, carPlay: true } });
  await prisma.model.create({ data: { brandId: b["丰田"].id, name: "锋兰达混动", slug: "toyota-frontlander-hybrid", level: "SUV", priceMin: 14.58, priceMax: 19.28, evType: "插混", salesVolume2025: 35000, imageUrl: null, motorPower: 83, motorTorque: 206, batteryCapacity: 5.2, batteryType: "三元锂", rangeCLTC: 28, fuelConsumption: 4.0, enginePower: 72, engineTorque: 142, length: 4485, width: 1825, height: 1620, wheelbase: 2640, weight: 1520, seats: 5, trunkVolume: 438, driveMode: "前驱", suspensionF: "麦弗逊", suspensionR: "扭力梁", adasLevel: "L2", screen: "10.25英寸", ota: false, carPlay: true, voltage: "400V" } });
  await prisma.model.create({ data: { brandId: b["本田"].id, name: "雅阁", slug: "honda-accord", level: "轿车", priceMin: 16.98, priceMax: 23.88, evType: "燃油", salesVolume2025: 72000, imageUrl: null, fuelType: "92#", fuelConsumption: 6.0, enginePower: 141, engineTorque: 260, length: 4980, width: 1862, height: 1449, wheelbase: 2830, weight: 1580, seats: 5, trunkVolume: 510, driveMode: "前驱", suspensionF: "麦弗逊", suspensionR: "多连杆", adasLevel: "L2", screen: "12.3英寸", ota: false, carPlay: true } });
  await prisma.model.create({ data: { brandId: b["本田"].id, name: "皓影", slug: "honda-breeze", level: "SUV", priceMin: 17.98, priceMax: 25.28, evType: "燃油", salesVolume2025: 120133, imageUrl: null, fuelType: "92#", fuelConsumption: 7.0, enginePower: 142, engineTorque: 243, length: 4716, width: 1866, height: 1691, wheelbase: 2701, weight: 1660, seats: 5, trunkVolume: 520, driveMode: "前驱", suspensionF: "麦弗逊", suspensionR: "多连杆", adasLevel: "L2", screen: "10.1英寸", ota: false, carPlay: true } });
  await prisma.model.create({ data: { brandId: b["日产"].id, name: "天籁", slug: "nissan-teana", level: "轿车", priceMin: 17.58, priceMax: 23.98, evType: "燃油", salesVolume2025: 38000, imageUrl: null, fuelType: "92#", fuelConsumption: 6.2, enginePower: 115, engineTorque: 197, length: 4906, width: 1850, height: 1447, wheelbase: 2825, weight: 1550, seats: 5, trunkVolume: 510, driveMode: "前驱", suspensionF: "麦弗逊", suspensionR: "扭力梁", adasLevel: "L2", screen: "8英寸", ota: false, carPlay: true } });
  await prisma.model.create({ data: { brandId: b["吉利银河"].id, name: "E8", slug: "geely-galaxy-e8", level: "轿车", priceMin: 16.58, priceMax: 22.88, evType: "纯电", salesVolume2025: 28000, imageUrl: null, motorType: "永磁同步", motorPower: 200, motorTorque: 380, batteryCapacity: 62, batteryType: "磷酸铁锂", rangeCLTC: 550, acceleration: 6.2, topSpeed: 190, length: 5010, width: 1920, height: 1465, wheelbase: 2925, weight: 2060, seats: 5, trunkVolume: 420, driveMode: "后驱", suspensionF: "双叉臂", suspensionR: "多连杆", chip: "高通8295", adasLevel: "L2+", screen: "45英寸8K", ota: true, carPlay: true, chargeFast: 20, chargeSlow: 8, chargePower: 150, voltage: "800V" } });
  await prisma.model.create({ data: { brandId: b["吉利"].id, name: "博越L", slug: "geely-boyue-l", level: "SUV", priceMin: 11.57, priceMax: 16.57, evType: "燃油", salesVolume2025: 232926, imageUrl: null, fuelType: "92#", fuelConsumption: 6.8, enginePower: 133, engineTorque: 290, length: 4670, width: 1900, height: 1705, wheelbase: 2777, weight: 1620, seats: 5, trunkVolume: 650, driveMode: "前驱", suspensionF: "麦弗逊", suspensionR: "多连杆", chip: "高通8155", adasLevel: "L2", screen: "13.2英寸", ota: true, carPlay: true } });
  await prisma.model.create({ data: { brandId: b["吉利"].id, name: "缤越", slug: "geely-coolray", level: "SUV", priceMin: 7.58, priceMax: 11.98, evType: "燃油", salesVolume2025: 133888, imageUrl: null, fuelType: "92#", fuelConsumption: 6.1, enginePower: 104, engineTorque: 235, length: 4330, width: 1800, height: 1609, wheelbase: 2600, weight: 1350, seats: 5, trunkVolume: 350, driveMode: "前驱", suspensionF: "麦弗逊", suspensionR: "扭力梁", adasLevel: null, screen: "8英寸", ota: false, carPlay: true } });
  await prisma.model.create({ data: { brandId: b["深蓝"].id, name: "SL03", slug: "deepal-sl03", level: "轿车", priceMin: 13.99, priceMax: 20.99, evType: "纯电", salesVolume2025: 25000, imageUrl: null, motorType: "永磁同步", motorPower: 160, motorTorque: 320, batteryCapacity: 58.1, batteryType: "磷酸铁锂", rangeCLTC: 515, acceleration: 6.2, topSpeed: 170, length: 4820, width: 1890, height: 1480, wheelbase: 2900, weight: 1830, seats: 5, trunkVolume: 420, driveMode: "后驱", suspensionF: "麦弗逊", suspensionR: "多连杆", chip: "高通8155", adasLevel: "L2+", screen: "14.6英寸", ota: true, carPlay: true, chargeFast: 25, chargeSlow: 7, chargePower: 70, voltage: "400V" } });
  await prisma.model.create({ data: { brandId: b["深蓝"].id, name: "S05", slug: "deepal-s05", level: "SUV", priceMin: 11.99, priceMax: 15.59, evType: "增程", salesVolume2025: 38000, imageUrl: null, motorPower: 160, motorTorque: 320, batteryCapacity: 27.28, batteryType: "磷酸铁锂", rangeCLTC: 100, topSpeed: 170, length: 4620, width: 1900, height: 1600, wheelbase: 2880, weight: 1780, seats: 5, trunkVolume: 470, driveMode: "后驱", suspensionF: "麦弗逊", suspensionR: "多连杆", chip: "高通8155", adasLevel: "L2", screen: "14.6英寸", ota: true, carPlay: true, chargeFast: 25, chargeSlow: 7, chargePower: 60, voltage: "400V" } });
  await prisma.model.create({ data: { brandId: b["广汽埃安"].id, name: "Aion V", slug: "gac-aion-v", level: "SUV", priceMin: 15.99, priceMax: 22.99, evType: "纯电", salesVolume2025: 35000, imageUrl: null, motorType: "永磁同步", motorPower: 180, motorTorque: 350, batteryCapacity: 67.7, batteryType: "磷酸铁锂", rangeCLTC: 580, topSpeed: 170, length: 4650, width: 1920, height: 1720, wheelbase: 2830, weight: 1900, seats: 5, trunkVolume: 500, driveMode: "前驱", suspensionF: "麦弗逊", suspensionR: "多连杆", adasLevel: "L2", screen: "14.6英寸", ota: true, carPlay: true, chargeSlow: 7.5, chargePower: 80, voltage: "400V" } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "海狮07 EV", slug: "byd-sealion-07-ev", level: "SUV", priceMin: 18.98, priceMax: 26.98, evType: "纯电", salesVolume2025: 23991, imageUrl: null, motorType: "永磁同步", motorPower: 170, motorTorque: 340, batteryCapacity: 71.8, batteryType: "磷酸铁锂", rangeCLTC: 610, acceleration: 5.7, topSpeed: 195, length: 4830, width: 1925, height: 1620, wheelbase: 2930, weight: 2130, seats: 5, trunkVolume: 520, driveMode: "后驱", suspensionF: "双叉臂", suspensionR: "五连杆", chip: "地平线征程3", adasLevel: "L2+", screen: "15.6英寸", ota: true, carPlay: true, chargeFast: 20, chargeSlow: 8, chargePower: 120, voltage: "800V" } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "海鸥2026款", slug: "byd-seagull-2026", level: "轿车", priceMin: 6.98, priceMax: 8.58, evType: "纯电", salesVolume2025: 307000, imageUrl: null, motorType: "永磁同步", motorPower: 55, motorTorque: 135, batteryCapacity: 30.08, batteryType: "磷酸铁锂", rangeCLTC: 305, topSpeed: 130, length: 3780, width: 1715, height: 1540, wheelbase: 2500, weight: 1200, seats: 4, trunkVolume: 930, driveMode: "前驱", suspensionF: "麦弗逊", suspensionR: "扭力梁", adasLevel: "L2", screen: "10.1英寸", ota: true, carPlay: true, chargeSlow: 4.5, voltage: "400V" } });
  await prisma.model.create({ data: { brandId: b["比亚迪"].id, name: "仰望U8", slug: "byd-yangwang-u8", level: "SUV", priceMin: 109.8, priceMax: 109.8, evType: "增程", salesVolume2025: 8000, imageUrl: null, motorPower: 880, motorTorque: 1280, batteryCapacity: 49.05, batteryType: "磷酸铁锂", rangeCLTC: 120, acceleration: 3.6, topSpeed: 200, length: 5319, width: 2050, height: 1930, wheelbase: 3050, weight: 3220, seats: 5, trunkVolume: 500, driveMode: "四驱", suspensionF: "双叉臂", suspensionR: "多连杆", chip: "比亚迪定制", adasLevel: "L2+", screen: "12.8英寸+后排", ota: true, carPlay: true, chargeFast: 30, chargeSlow: 8, chargePower: 110, voltage: "800V" } });
  // === 用户 ===
  const u1 = await prisma.user.create({ data: { phone: "13800138001", password: await hashPassword("123456"), nickname: "普通用户", role: "user" } });
  const u2 = await prisma.user.create({ data: { phone: "13800138000", password: await hashPassword("admin123"), nickname: "管理员", role: "admin" } });
  const u3 = await prisma.user.create({ data: { phone: "13800138002", password: await hashPassword("123456"), nickname: "测试用户", role: "user" } });

  // === 资讯 ===
  await prisma.article.createMany({
    data: [
      { title: "比亚迪汉EV 2026款深度评测：全面进化的标杆", slug: "byd-han-ev-2026-review", content: "作为比亚迪旗舰轿车，汉EV 2026款在续航、智能驾驶和舒适性方面全面升级。续航提升至715km CLTC，搭载天神之眼高阶智驾系统，内饰用料和做工再上一个台阶。", type: "review", modelId: (await prisma.model.findFirst({ where: { slug: "byd-han-ev" } }))!.id, author: "车友荟编辑部", publishedAt: new Date("2026-05-01") },
      { title: "2025年新能源车市盘点：渗透率突破50%", slug: "2025-nev-market-review", content: "2025年中国新能源汽车销量突破1600万辆，渗透率首次超过50%，标志着新能源车正式成为市场主流。比亚迪、吉利、特斯拉三强格局稳固。", type: "news", author: "车友荟编辑部", publishedAt: new Date("2026-01-15") },
      { title: "小米SU7 vs 特斯拉Model 3：谁是20万级纯电轿车之王？", slug: "xiaomi-su7-vs-tesla-model3", content: "两款20万+纯电轿车的正面碰撞。小米SU7凭借更智能的座舱和800V快充，特斯拉Model 3凭借成熟的智驾和品牌力，各有千秋。", type: "review", author: "车友荟编辑部", publishedAt: new Date("2026-03-20") },
      { title: "2026年最值得期待的10款新能源车", slug: "2026-top10-nev-preview", content: "从比亚迪全新MPV到蔚来NT3平台新车，2026年将有大量重磅新能源车上市，竞争将进一步白热化。", type: "guide", author: "车友荟编辑部", publishedAt: new Date("2026-04-10") },
      { title: "插混还是增程？一文看懂两种混动技术", slug: "phev-vs-erev-explained", content: "插电混动和增程式混动有什么区别？哪种更适合你？从技术原理到实际用车场景，全面解析两种混动路线的优劣。", type: "guide", author: "车友荟编辑部", publishedAt: new Date("2026-02-28") },
    ],
  });

  // === 二手车源 ===
  const hanEv = await prisma.model.findFirst({ where: { slug: "byd-han-ev" } });
  const modelY = await prisma.model.findFirst({ where: { slug: "tesla-model-y" } });
  const dolphin = await prisma.model.findFirst({ where: { slug: "byd-dolphin" } });
  if (hanEv) await prisma.carSource.create({ data: { modelId: hanEv.id, sellerId: u3.id, year: 2023, mileage: 3.5, price: 15.8, city: "深圳", description: "汉EV 2023款旗舰型，3.5万公里，车况精品，可看车", images: [], status: "active", publishedAt: new Date() } });
  if (modelY) await prisma.carSource.create({ data: { modelId: modelY.id, sellerId: u1.id, year: 2024, mileage: 1.2, price: 21.5, city: "北京", description: "Model Y 2024款长续航版，1.2万公里，准新车", images: [], status: "active", publishedAt: new Date() } });
  if (dolphin) await prisma.carSource.create({ data: { modelId: dolphin.id, sellerId: u3.id, year: 2024, mileage: 0.8, price: 8.9, city: "上海", description: "海豚时尚版，0.8万公里，几乎全新", images: [], status: "active", publishedAt: new Date() } });

  console.log("✅ 种子数据创建完成！");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
